export const FINISH_STARTING_UP = 'FINISH_STARTING_UP';

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';

export const ADD_ERROR = 'ADD_ERROR';

export const NAVIGATE_TO = 'NAVIGATE_TO';

export const SET_APP = 'SET_APP';

export const FETCH_ALL_LANGUAGES = 'FETCH_ALL_LANGUAGES';
export const FETCH_ALL_LANGUAGES_SUCCESS = 'FETCH_ALL_LANGUAGES_SUCCESS';
export const FETCH_ALL_LANGUAGES_FAILURE = 'FETCH_ALL_LANGUAGES_FAILURE';

export const FETCH_POS = 'FETCH_POS';
export const SET_POS = 'SET_POS';

export const SET_MODAL = 'SET_MODAL';
export const CLEAR_MODAL = 'CLEAR_MODAL';
