export const FETCH_ALL_QUIZZES = 'FETCH_ALL_QUIZZES';
export const FETCH_ALL_QUIZZES_START = 'FETCH_ALL_QUIZZES_START';
export const FETCH_ALL_QUIZZES_SUCCESS = 'FETCH_ALL_QUIZZES_SUCCESS';
export const FETCH_ALL_QUIZZES_FAILURE = 'FETCH_ALL_QUIZZES_FAILURE';

export const SELECT_QUIZ = 'SELECT_QUIZ';

export const CREATE_QUIZ = 'CREATE_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';

export const FETCH_QUIZ = 'FETCH_QUIZ';
export const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAIURE = 'FETCH_QUIZ_FAIURE';

export const FETCH_MATCHING_REGIMES = 'FETCH_MATCHING_REGIMES';
export const FETCH_MATCHING_REGIMES_SUCCESS = 'FETCH_MATCHING_REGIMES_SUCCESS';

export const FETCH_QUIZ_REGIMES = 'FETCH_QUIZ_REGIMES';
export const FETCH_QUIZ_REGIMES_SUCCESS = 'FETCH_QUIZ_REGIMES_SUCCESS';

export const FETCH_QUIZ_SETTINGS = 'FETCH_QUIZ_SETTINGS';
export const FETCH_QUIZ_SETTINGS_SUCCESS = 'FETCH_QUIZ_SETTINGS_SUCCESS';
export const UPDATE_QUIZ_SETTINGS = 'UPDATE_QUIZ_SETTINGS';
export const UPDATE_QUIZ_SETTINGS_SUCCESS = 'UPDATE_QUIZ_SETTINGS_SUCCESS';

export const FETCH_ALL_QUIZZES_BY_LANGUAGE = 'FETCH_ALL_QUIZZES_BY_LANGUAGE';
export const FETCH_ALL_QUIZZES_BY_LANGUAGE_START = 'FETCH_ALL_QUIZZES_BY_LANGUAGE_START';
export const FETCH_ALL_QUIZZES_BY_LANGUAGE_SUCCESS = 'FETCH_ALL_QUIZZES_BY_LANGUAGE_SUCCESS';
export const FETCH_ALL_QUIZZES_BY_LANGUAGE_FAILURE = 'FETCH_ALL_QUIZZES_BY_LANGUAGE_FAILURE';

export const CREATE_QUIZ_FOR_MEANING_TO_QUIZ_RECORD = 'CREATE_QUIZ_FOR_MEANING_TO_QUIZ_RECORD';
export const CREATE_QUIZ_FOR_MEANING_TO_QUIZ_RECORD_SUCCESS = 'CREATE_QUIZ_FOR_MEANING_TO_QUIZ_RECORD_SUCCESS';
