export const FETCH_ALL_QUIZZES = 'FETCH_ALL_QUIZZES';
export const FETCH_ALL_QUIZZES_START = 'FETCH_ALL_QUIZZES_START';
export const FETCH_ALL_QUIZZES_SUCCESS = 'FETCH_ALL_QUIZZES_SUCCESS';
export const FETCH_ALL_QUIZZES_FAILURE = 'FETCH_ALL_QUIZZES_FAILURE';

export const SELECT_QUIZ = 'SELECT_QUIZ';
