export const FETCH_ALL_QUIZZES = 'FETCH_ALL_QUIZZES';
export const FETCH_ALL_QUIZZES_START = 'FETCH_ALL_QUIZZES_START';
export const FETCH_ALL_QUIZZES_SUCCESS = 'FETCH_ALL_QUIZZES_SUCCESS';
export const FETCH_ALL_QUIZZES_FAILURE = 'FETCH_ALL_QUIZZES_FAILURE';

export const SELECT_QUIZ = 'SELECT_QUIZ';

export const CREATE_QUIZ = 'CREATE_QUIZ';
export const UPDATE_QUIZ = 'UPDATE_QUIZ';
export const DELETE_QUIZ = 'DELETE_QUIZ';

export const FETCH_QUIZ = 'FETCH_QUIZ';
export const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_FAIURE = 'FETCH_QUIZ_FAIURE';
