export const FETCH_QUIZ_RECORDS = 'FETCH_QUIZ_RECORDS';
export const FETCH_QUIZ_RECORDS_SUCCESS = 'FETCH_QUIZ_RECORDS_SUCCESS';

export const SELECT_QUIZ_RECORD = 'SELECT_QUIZ_RECORD';

export const CREATE_QUIZ_RECORD = 'CREATE_QUIZ_RECORD';
export const DELETE_QUIZ_RECORD = 'DELETE_QUIZ_RECORD';

export const FETCH_QUIZ_RECORD = 'FETCH_QUIZ_RECORD';
export const FETCH_QUIZ_RECORD_START = 'FETCH_QUIZ_RECORD_START';
export const FETCH_QUIZ_RECORD_SUCCESS = 'FETCH_QUIZ_RECORD_SUCCESS';
export const FETCH_QUIZ_RECORD_FAILURE = 'FETCH_QUIZ_RECORD_FAILURE';

export const SET_QUIZ_RECORD_EDITING = 'SET_QUIZ_RECORD_EDITING';

export const SET_QUIZ_RECORD_EDIT_MODAL_TYPE = 'SET_QUIZ_RECORD_EDIT_MODAL_TYPE';
export const SHOULD_SHOW_QUIZ_RECORD_EDIT_MODAL = 'SHOULD_SHOW_QUIZ_RECORD_EDIT_MODAL';
export const UPDATE_QUIZ_RECORD_MAIN_FORM = 'UPDATE_QUIZ_RECORD_MAIN_FORM';
export const UPDATE_QUIZ_RECORD = 'UPDATE_QUIZ_RECORD';