export const FETCH_WORDS_LIST = 'FETCH_WORD_LIST';
export const FETCH_WORDS_LIST_SUCCESS = 'FETCH_WORD_LIST_SUCCESS';

export const FETCH_WORD = 'FETCH_WORD';
export const FETCH_WORD_START = 'FETCH_WORD_START';
export const FETCH_WORD_SUCCESS = 'FETCH_WORD_SUCCESS';
export const FETCH_WORD_FAILURE = 'FETCH_WORD_FAILURE';

export const SELECT_WORD = 'SELECT_WORD';

export const CREATE_WORD = 'CREATE_WORD';

export const DELETE_SELECTED_WORD = 'DELETE_SELECTED_WORD';

export const SET_WORD_EDITING = 'SET_WORD_EDITING';
export const UPDATE_WORD_MAIN_FORM = 'UPDATE_WORD_MAIN_FORM';
export const UPDATE_WORD_ELEMENT = 'UPDATE_WORD_ELEMENT';
export const UPDATE_WORD = 'UPDATE_WORD';
export const SHOULD_SHOW_WORD_EDIT_MODAL = 'SHOULD_SHOW_WORD_EDIT_MODAL';
export const SET_WORD_EDIT_MODAL_TYPE = 'SET_WORD_EDIT_MODAL_TYPE';

export const FETCH_POS = 'FETCH_POS';
export const SET_POS = 'SET_POS';
