export const FETCH_WORDS_LIST = 'FETCH_WORD_LIST';
export const FETCH_WORDS_LIST_SUCCESS = 'FETCH_WORD_LIST_SUCCESS';

export const FETCH_WORD = 'FETCH_WORD';
export const FETCH_WORD_START = 'FETCH_WORD_START';
export const FETCH_WORD_SUCCESS = 'FETCH_WORD_SUCCESS';
export const FETCH_WORD_FAILURE = 'FETCH_WORD_FAILURE';

export const SELECT_WORD = 'SELECT_WORD';
